### ISSUE TITLE
zone list spawn2

### ISSUE THREAD

**Issue by xackery** [ProjectEQ/peq-expansions#11]
This is a master list of zones, for spawn2. You can search on top, but if you aren't sure if a zone exists, we can use this as a table of contents as we add zones to know which ones are still missing.

### Classic

- [x] airplane #58
- [x] akanon #10 
- [x] arena #9 
- [x] befallen #8 
- [x] beholder #7 
- [x] blackburrow #6 
- [x] butcher #5 
- [x] cauldron #4 
- [x] cazicthule #59
- [x] commons #2 
- [x] crushbone #49
- [x] eastkarana #48
- [x] ecommons #3 
- [x] erudnext #46
- [x] erudnint #45
- [x] erudsxing #44
- [x] everfrost #47
- [x] fearplane #60
- [x] feerrott  #43
- [x] felwithea #42
- [x] felwitheb #41
- [x] freporte #61
- [x] freportn #62
- [x] freportw #63
- [x] gfaydark #40
- [x] grobb #39
- [x] gukbottom #64
- [x] guktop #65
- [x] halas #38
- [x] hateplane #66
- [x] highkeep #67
- [x] highpasshold #36
- [x] highpass #37
- [x] hole #68
- [x] innothule  #69
- [x] kaladima #35
- [x] kaladimb #34
- [x] kedge #70
- [x] kerraridge #33
- [x] kithicor #71
- [x] lakerathe #72
- [x] highpass #37
- [x] lavastorm #73
- [x] nektulos #74
- [x] lfaydark #75
- [x] mistmoore #76
- [x] misty #32
- [x] najena #77
- [x] neriaka #31
- [x] neriakb #15 
- [x] neriakc #78
- [x] northkarana #79
- [x] nro #80
- [x] oasis #81
- [x] oggok #30
- [x] oot #29
- [x] paineel #82
- [x] paw #83
- [x] permafrost #84
- [x] qcat #28
- [x] qey2hh1 #85
- [x] qeynos #27
- [x] qeynos2 #26
- [x] qeytoqrg #86
- [x] qrg #25
- [x] rathemtn #18
- [x] rivervale #21 
- [x] runneye #87
- [x] runnyeye #88
- [x] soldunga #89
- [x] soldungb #90
- [x] southkarana #91
- [x] sro #92
- [x] steamfont #20 
- [x] tox #93
- [x] unrest #94

## Kunark

- [ ] burningwood	1	99
- [ ] citymist	1	99
- [ ] dalnir	1	99
- [ ] dreadlands	1	99
- [ ] cabeast	1	99
- [ ] emeraldjungle	1	99
- [ ] fieldofbone	1	99
- [ ] firiona	1	99
- [ ] frontiermtns	1	99
- [ ] charasis	1	99
- [ ] kaesora	1	99
- [ ] karnor	1	99
- [ ] kurn	1	99
- [ ] lakeofillomen	1	99
- [ ] nurga	1	5
- [ ] sebilis	1	24
- [ ] skyfire	1	99
- [ ] swampofnohope	1	99
- [ ] droga	1	5
- [ ] overthere	1	99
- [ ] timorous	1	99
- [ ] trakanon	1	99
- [ ] veeshan	1	6
- [ ] warsilkswood	1	99
- [ ] cabwest	1	99

**Comment by TheGrandPackard** [comment]
`soltemple` is missing from this list. I believe `Terblyn Zelbus` was added in Velious to sell the Wizard Translocate spells

**Comment by xackery** [comment]
closing for now. We can do a new approach later
