### ISSUE TITLE
Classic Tradeskills

### ISSUE THREAD

**Issue by xackery** [ProjectEQ/peq-expansions#12]
- [ ] https://fvproject.com/Alchemy
- [ ] https://fvproject.com/Baking
- [ ] https://fvproject.com/Blacksmithing
- [ ] https://fvproject.com/Brewing
- [ ] https://fvproject.com/Fletching
- [ ] https://fvproject.com/Jewelry_Making
- [ ] https://fvproject.com/Poison_Making
- [ ] https://fvproject.com/Pottery
- [ ] https://fvproject.com/Research
- [ ] https://fvproject.com/Tailoring
- [ ] https://fvproject.com/Tinkering

**Comment by TurmoilToad** [comment]
Classic Alchemy

-- tradeskill recipes ALCHEMY prior to 17 FEB 2000

----------------------------------------------------
	-- SELECT * FROM tradeskill_recipe 
	-- WHERE tradeskill = 59 AND enabled = 1;
----------------------------------------------------

INSERT INTO `tradeskill_recipe` (`id`, `name`, `tradeskill`, `skillneeded`, `trivial`, `nofail`, `replace_container`, `notes`, `must_learn`, `quest`, `enabled`, `min_expansion`, `max_expansion`)
VALUES
	(1028, '10 Dose Potion Of Charming Deceit', 59, 0, 0, 1, 0, NULL, 0, 0, 1, 0, 0),
	(1031, '10 Dose Potion Of Copal\'s Demise', 59, 0, 0, 1, 0, NULL, 0, 0, 1, 0, 0),
	(1033, '10 Dose Potion Of Fleeting Languor', 59, 0, 0, 1, 0, NULL, 0, 0, 1, 0, 0),
	(1034, '10 Dose Potion Of Gnomish Boils', 59, 0, 0, 1, 0, NULL, 0, 0, 1, 0, 0),
	(1035, '10 Dose Potion Of Gorging Toxin', 59, 0, 0, 1, 0, NULL, 0, 0, 1, 0, 0),
	(1037, '10 Dose Potion Of Gulon\'s Impunity', 59, 0, 0, 1, 0, NULL, 0, 0, 1, 0, 0),
	(1052, '10 Dose Potion Of Spurn Affliction', 59, 0, 0, 1, 0, NULL, 0, 0, 1, 0, 0),
	(1058, '10 Dose Potion Of Troll\'s Essence', 59, 0, 0, 1, 0, NULL, 0, 0, 1, 0, 0),
	(1062, '10 Dose Potion Of Vox\'s Vitality', 59, 0, 0, 1, 0, NULL, 0, 0, 1, 0, 0),
	(1066, '10 Dose Soul Of The Incorporeal', 59, 0, 0, 1, 0, NULL, 0, 0, 1, 0, 0),
	(1071, '10 Doses Of Frosty Insurgency', 59, 0, 0, 1, 0, NULL, 0, 0, 1, 0, 0),
	(1080, '10 Doses Of Undead\'s Recourse', 59, 0, 0, 1, 0, NULL, 0, 0, 1, 0, 0),
	(1163, '5 Dose Potion Of Charming Deceit', 59, 0, 0, 1, 0, NULL, 0, 0, 1, 0, 0),
	(1166, '5 Dose Potion Of Copal\'s Demise', 59, 0, 0, 1, 0, NULL, 0, 0, 1, 0, 0),
	(1168, '5 Dose Potion Of Fleeting Languor', 59, 0, 0, 1, 0, NULL, 0, 0, 1, 0, 0),
	(1169, '5 Dose Potion Of Frosty Insurgency', 59, 0, 0, 1, 0, NULL, 0, 0, 1, 0, 0),
	(1170, '5 Dose Potion Of Gnomish Boils', 59, 0, 0, 1, 0, NULL, 0, 0, 1, 0, 0),
	(1171, '5 Dose Potion Of Gorging Toxin', 59, 0, 0, 1, 0, NULL, 0, 0, 1, 0, 0),
	(1173, '5 Dose Potion Of Gulon\'s Impunity', 59, 0, 0, 1, 0, NULL, 0, 0, 1, 0, 0),
	(1189, '5 Dose Potion Of Spurn Affliction', 59, 0, 0, 1, 0, NULL, 0, 0, 1, 0, 0),
	(1196, '5 Dose Potion Of Troll\'s Essence', 59, 0, 0, 1, 0, NULL, 0, 0, 1, 0, 0),
	(1197, '5 Dose Potion Of Undead\'s Recourse', 59, 0, 0, 1, 0, NULL, 0, 0, 1, 0, 0),
	(1201, '5 Dose Potion Of Vox\'s Vitality', 59, 0, 0, 1, 0, NULL, 0, 0, 1, 0, 0),
	(1345, 'Potion Of Charming Deceit', 59, 0, 22, 0, 0, NULL, 0, 0, 1, 0, 0),
	(1348, 'Potion Of Copal\'s Demise', 59, 0, 90, 0, 0, NULL, 0, 0, 1, 0, 0),
	(1350, 'Potion Of Fleeting Languor', 59, 0, 47, 0, 0, NULL, 0, 0, 1, 0, 0),
	(1351, 'Potion Of Frosty Insurgency', 59, 0, 42, 0, 0, NULL, 0, 0, 1, 0, 0),
	(1352, 'Potion Of Gnomish Boils', 59, 0, 57, 0, 0, NULL, 0, 0, 1, 0, 0),
	(1353, 'Potion Of Gorging Toxin', 59, 0, 47, 0, 0, NULL, 0, 0, 1, 0, 0),
	(1356, 'Potion Of Gulon\'s Impunity', 59, 0, 83, 0, 0, NULL, 0, 0, 1, 0, 0),
	(1375, 'Potion Of Spurn Affliction', 59, 0, 32, 0, 0, NULL, 0, 0, 1, 0, 0),
	(1381, 'Potion Of Troll\'s Essence', 59, 0, 27, 0, 0, NULL, 0, 0, 1, 0, 0),
	(1382, 'Potion Of Undead\'s Recourse', 59, 0, 76, 0, 0, NULL, 0, 0, 1, 0, 0),
	(1386, 'Potion Of Vox\'s Vitality', 59, 0, 63, 0, 0, NULL, 0, 0, 1, 0, 0),
	(1389, 'Potion Soul Of The Incorporeal', 59, 0, 70, 0, 0, NULL, 0, 0, 1, 0, 0),
	(25154, 'Potion Skin of Ro', 59, 0, 42, 0, 0, 'Created by TurmoilToad', 32, 0, 1, 0, 0);

-- tradeskill recipe entries ALCHEMY prior to 17 FEB 2000

----------------------------------------------------
	-- SELECT tse.*
	-- FROM tradeskill_recipe_entries AS tse
	-- INNER JOIN tradeskill_recipe AS tr
	-- ON tr.id = tse.recipe_id
	-- WHERE tr.enabled = 1 AND tr.tradeskill = 59
----------------------------------------------------

INSERT INTO `tradeskill_recipe_entries` (`id`, `recipe_id`, `item_id`, `successcount`, `failcount`, `componentcount`, `salvagecount`, `iscontainer`)
VALUES
	(8559, 1028, 16453, 0, 0, 10, 10, 0),
	(8560, 1028, 14388, 10, 0, 0, 0, 0),
	(8561, 1028, 17771, 0, 0, 0, 0, 1),
	(8562, 1028, 17811, 0, 0, 0, 0, 1),
	(8571, 1031, 16466, 0, 0, 10, 10, 0),
	(8572, 1031, 14458, 10, 0, 0, 0, 0),
	(8573, 1031, 17771, 0, 0, 0, 0, 1),
	(8574, 1031, 17811, 0, 0, 0, 0, 1),
	(8579, 1033, 16462, 0, 0, 10, 10, 0),
	(8580, 1033, 14397, 10, 0, 0, 0, 0),
	(8581, 1033, 17771, 0, 0, 0, 0, 1),
	(8582, 1033, 17811, 0, 0, 0, 0, 1),
	(8583, 1034, 16460, 0, 0, 10, 10, 0),
	(8584, 1034, 14395, 10, 0, 0, 0, 0),
	(8585, 1034, 17771, 0, 0, 0, 0, 1),
	(8586, 1034, 17811, 0, 0, 0, 0, 1),
	(8587, 1035, 16458, 0, 0, 10, 10, 0),
	(8588, 1035, 14393, 10, 0, 0, 0, 0),
	(8589, 1035, 17771, 0, 0, 0, 0, 1),
	(8590, 1035, 17811, 0, 0, 0, 0, 1),
	(8595, 1037, 16465, 0, 0, 10, 10, 0),
	(8596, 1037, 14457, 10, 0, 0, 0, 0),
	(8597, 1037, 17771, 0, 0, 0, 0, 1),
	(8598, 1037, 17811, 0, 0, 0, 0, 1),
	(8655, 1052, 16455, 0, 0, 10, 10, 0),
	(8656, 1052, 14390, 10, 0, 0, 0, 0),
	(8657, 1052, 17771, 0, 0, 0, 0, 1),
	(8658, 1052, 17811, 0, 0, 0, 0, 1),
	(8679, 1058, 16454, 0, 0, 10, 10, 0),
	(8680, 1058, 14389, 10, 0, 0, 0, 0),
	(8681, 1058, 17771, 0, 0, 0, 0, 1),
	(8682, 1058, 17811, 0, 0, 0, 0, 1),
	(8695, 1062, 16461, 0, 0, 10, 10, 0),
	(8696, 1062, 14396, 10, 0, 0, 0, 0),
	(8697, 1062, 17771, 0, 0, 0, 0, 1),
	(8698, 1062, 17811, 0, 0, 0, 0, 1),
	(8711, 1066, 16463, 0, 0, 10, 10, 0),
	(8712, 1066, 14398, 10, 0, 0, 0, 0),
	(8713, 1066, 17771, 0, 0, 0, 0, 1),
	(8714, 1066, 17811, 0, 0, 0, 0, 1),
	(8731, 1071, 16457, 0, 0, 10, 10, 0),
	(8732, 1071, 14392, 10, 0, 0, 0, 0),
	(8733, 1071, 17771, 0, 0, 0, 0, 1),
	(8734, 1071, 17811, 0, 0, 0, 0, 1),
	(8767, 1080, 16464, 0, 0, 10, 10, 0),
	(8768, 1080, 14399, 10, 0, 0, 0, 0),
	(8769, 1080, 17771, 0, 0, 0, 0, 1),
	(8770, 1080, 17811, 0, 0, 0, 0, 1),
	(9099, 1163, 16453, 0, 0, 5, 5, 0),
	(9100, 1163, 14169, 5, 0, 0, 0, 0),
	(9101, 1163, 17771, 0, 0, 0, 0, 1),
	(9102, 1163, 17811, 0, 0, 0, 0, 1),
	(9111, 1166, 16466, 0, 0, 5, 5, 0),
	(9112, 1166, 14182, 5, 0, 0, 0, 0),
	(9113, 1166, 17771, 0, 0, 0, 0, 1),
	(9114, 1166, 17811, 0, 0, 0, 0, 1),
	(9119, 1168, 16462, 0, 0, 5, 5, 0),
	(9120, 1168, 14178, 5, 0, 0, 0, 0),
	(9121, 1168, 17771, 0, 0, 0, 0, 1),
	(9122, 1168, 17811, 0, 0, 0, 0, 1),
	(9123, 1169, 16457, 0, 0, 5, 5, 0),
	(9124, 1169, 14173, 5, 0, 0, 0, 0),
	(9125, 1169, 17771, 0, 0, 0, 0, 1),
	(9126, 1169, 17811, 0, 0, 0, 0, 1),
	(9127, 1170, 16460, 0, 0, 5, 5, 0),
	(9128, 1170, 14176, 5, 0, 0, 0, 0),
	(9129, 1170, 17771, 0, 0, 0, 0, 1),
	(9130, 1170, 17811, 0, 0, 0, 0, 1),
	(9131, 1171, 16458, 0, 0, 5, 5, 0),
	(9132, 1171, 14174, 5, 0, 0, 0, 0),
	(9133, 1171, 17771, 0, 0, 0, 0, 1),
	(9134, 1171, 17811, 0, 0, 0, 0, 1),
	(9139, 1173, 16465, 0, 0, 5, 5, 0),
	(9140, 1173, 14181, 5, 0, 0, 0, 0),
	(9141, 1173, 17771, 0, 0, 0, 0, 1),
	(9142, 1173, 17811, 0, 0, 0, 0, 1),
	(9202, 1189, 16455, 0, 0, 5, 5, 0),
	(9203, 1189, 14171, 5, 0, 0, 0, 0),
	(9204, 1189, 17771, 0, 0, 0, 0, 1),
	(9205, 1189, 17811, 0, 0, 0, 0, 1),
	(9230, 1196, 16454, 0, 0, 5, 5, 0),
	(9231, 1196, 14170, 5, 0, 0, 0, 0),
	(9232, 1196, 17771, 0, 0, 0, 0, 1),
	(9233, 1196, 17811, 0, 0, 0, 0, 1),
	(9234, 1197, 16464, 0, 0, 5, 5, 0),
	(9235, 1197, 14180, 5, 0, 0, 0, 0),
	(9236, 1197, 17771, 0, 0, 0, 0, 1),
	(9237, 1197, 17811, 0, 0, 0, 0, 1),
	(9250, 1201, 16461, 0, 0, 5, 5, 0),
	(9251, 1201, 14177, 5, 0, 0, 0, 0),
	(9252, 1201, 17771, 0, 0, 0, 0, 1),
	(9253, 1201, 17811, 0, 0, 0, 0, 1),
	(10444, 1345, 16509, 0, 0, 1, 1, 0),
	(10445, 1345, 16532, 0, 0, 1, 1, 0),
	(10446, 1345, 16453, 1, 0, 0, 0, 0),
	(10447, 1345, 17770, 0, 0, 0, 0, 1),
	(10448, 1345, 17771, 0, 0, 0, 0, 1),
	(10449, 1345, 17811, 0, 0, 0, 0, 1),
	(10450, 1345, 17901, 0, 0, 0, 0, 1),
	(10467, 1348, 16522, 0, 0, 1, 1, 0),
	(10468, 1348, 16536, 0, 0, 1, 1, 0),
	(10469, 1348, 16466, 1, 0, 0, 0, 0),
	(10470, 1348, 17770, 0, 0, 0, 0, 1),
	(10471, 1348, 17771, 0, 0, 0, 0, 1),
	(10472, 1348, 17811, 0, 0, 0, 0, 1),
	(10473, 1348, 17901, 0, 0, 0, 0, 1),
	(10481, 1350, 13768, 0, 0, 1, 1, 0),
	(10482, 1350, 16518, 0, 0, 1, 1, 0),
	(10483, 1350, 16462, 1, 0, 0, 0, 0),
	(10484, 1350, 17770, 0, 0, 0, 0, 1),
	(10485, 1350, 17771, 0, 0, 0, 0, 1),
	(10486, 1350, 17811, 0, 0, 0, 0, 1),
	(10487, 1350, 17901, 0, 0, 0, 0, 1),
	(10488, 1351, 13761, 0, 0, 1, 1, 0),
	(10489, 1351, 16513, 0, 0, 1, 1, 0),
	(10490, 1351, 16457, 1, 0, 0, 0, 0),
	(10491, 1351, 17770, 0, 0, 0, 0, 1),
	(10492, 1351, 17771, 0, 0, 0, 0, 1),
	(10493, 1351, 17811, 0, 0, 0, 0, 1),
	(10494, 1351, 17901, 0, 0, 0, 0, 1),
	(10495, 1352, 13069, 0, 0, 1, 1, 0),
	(10496, 1352, 16516, 0, 0, 1, 1, 0),
	(10497, 1352, 35794, 0, 0, 1, 1, 0),
	(10498, 1352, 16460, 1, 0, 0, 0, 0),
	(10499, 1352, 17770, 0, 0, 0, 0, 1),
	(10500, 1352, 17771, 0, 0, 0, 0, 1),
	(10501, 1352, 17811, 0, 0, 0, 0, 1),
	(10502, 1352, 17901, 0, 0, 0, 0, 1),
	(10503, 1353, 13260, 0, 0, 1, 1, 0),
	(10504, 1353, 16514, 0, 0, 1, 1, 0),
	(10505, 1353, 16458, 1, 0, 0, 0, 0),
	(10506, 1353, 17770, 0, 0, 0, 0, 1),
	(10507, 1353, 17771, 0, 0, 0, 0, 1),
	(10508, 1353, 17811, 0, 0, 0, 0, 1),
	(10509, 1353, 17901, 0, 0, 0, 0, 1),
	(10526, 1356, 10300, 0, 0, 1, 1, 0),
	(10527, 1356, 16521, 0, 0, 1, 1, 0),
	(10528, 1356, 16465, 1, 0, 0, 0, 0),
	(10529, 1356, 17770, 0, 0, 0, 0, 1),
	(10530, 1356, 17771, 0, 0, 0, 0, 1),
	(10531, 1356, 17811, 0, 0, 0, 0, 1),
	(10532, 1356, 17901, 0, 0, 0, 0, 1),
	(10667, 1375, 13074, 0, 0, 1, 1, 0),
	(10668, 1375, 16511, 0, 0, 1, 1, 0),
	(10669, 1375, 16455, 1, 0, 0, 0, 0),
	(10670, 1375, 17770, 0, 0, 0, 0, 1),
	(10671, 1375, 17771, 0, 0, 0, 0, 1),
	(10672, 1375, 17811, 0, 0, 0, 0, 1),
	(10673, 1375, 17901, 0, 0, 0, 0, 1),
	(10710, 1381, 13143, 0, 0, 1, 1, 0),
	(10711, 1381, 16510, 0, 0, 1, 1, 0),
	(10712, 1381, 16454, 1, 0, 0, 0, 0),
	(10713, 1381, 17770, 0, 0, 0, 0, 1),
	(10714, 1381, 17771, 0, 0, 0, 0, 1),
	(10715, 1381, 17811, 0, 0, 0, 0, 1),
	(10716, 1381, 17901, 0, 0, 0, 0, 1),
	(10717, 1382, 16520, 0, 0, 1, 1, 0),
	(10718, 1382, 16535, 0, 0, 1, 1, 0),
	(10719, 1382, 16464, 1, 0, 0, 0, 0),
	(10720, 1382, 17770, 0, 0, 0, 0, 1),
	(10721, 1382, 17771, 0, 0, 0, 0, 1),
	(10722, 1382, 17811, 0, 0, 0, 0, 1),
	(10723, 1382, 17901, 0, 0, 0, 0, 1),
	(10746, 1386, 13373, 0, 0, 1, 1, 0),
	(10747, 1386, 16517, 0, 0, 1, 1, 0),
	(10748, 1386, 16461, 1, 0, 0, 0, 0),
	(10749, 1386, 17770, 0, 0, 0, 0, 1),
	(10750, 1386, 17771, 0, 0, 0, 0, 1),
	(10751, 1386, 17811, 0, 0, 0, 0, 1),
	(10752, 1386, 17901, 0, 0, 0, 0, 1),
	(10767, 1389, 13094, 0, 0, 1, 1, 0),
	(10768, 1389, 16519, 0, 0, 1, 1, 0),
	(10769, 1389, 16463, 1, 0, 0, 0, 0),
	(10770, 1389, 17770, 0, 0, 0, 0, 1),
	(10771, 1389, 17771, 0, 0, 0, 0, 1),
	(10772, 1389, 17811, 0, 0, 0, 0, 1),
	(10773, 1389, 17901, 0, 0, 0, 0, 1),
	(252069, 25154, 17770, 0, 0, 0, 0, 1),
	(252070, 25154, 17771, 0, 0, 0, 0, 1),
	(252071, 25154, 17811, 0, 0, 0, 0, 1),
	(252072, 25154, 17901, 0, 0, 0, 0, 1),
	(252073, 25154, 16515, 0, 0, 1, 1, 0),
	(252074, 25154, 16534, 0, 0, 1, 1, 0),
	(252075, 25154, 16459, 1, 0, 0, 0, 0);

**Comment by xackery** [comment]
#113  moving to global loot just to reference
